const FETCH_CRYPTOS_REQUEST = 'FETCH_CRYPTOS_REQUEST';
const FETCH_CRYPTOS_SUCCESS = 'FETCH_CRYPTOS_SUCCESS';
const FETCH_CRYPTOS_FAILURE = 'FETCH_CRYPTOS_FAILURE';
const FETCH_METALS_REQUEST = 'FETCH_METALS_REQUEST';
const FETCH_METALS_SUCCESS = 'FETCH_METALS_SUCCESS';
const FETCH_METALS_FAILURE = 'FETCH_METALS_FAILURE';
const FETCH_STOCKS_REQUEST = 'FETCH_STOCKS_REQUEST';
const FETCH_STOCKS_SUCCESS = 'FETCH_STOCKS_SUCCESS';
const FETCH_STOCKS_FAILURE = 'FETCH_STOCKS_FAILURE';
const UPDATE_PORTFOLIO_VALUES = 'UPDATE_PORTFOLIO_VALUES';
const UPDATE_PORTFOLIO_ALLOCATIONS = 'UPDATE_PORTFOLIO_ALLOCATIONS';

export {
  FETCH_CRYPTOS_REQUEST,
  FETCH_CRYPTOS_SUCCESS,
  FETCH_CRYPTOS_FAILURE,
  FETCH_METALS_REQUEST,
  FETCH_METALS_SUCCESS,
  FETCH_METALS_FAILURE,
  FETCH_STOCKS_REQUEST,
  FETCH_STOCKS_SUCCESS,
  FETCH_STOCKS_FAILURE,
  UPDATE_PORTFOLIO_VALUES,
  UPDATE_PORTFOLIO_ALLOCATIONS,
};
